export type Input = {
    SearchTerm: string,
    AB_SAYT_ports: string,
    OtherPortSearchStr: string,
    legType: string,
    cult: string,
    AB_user_iso_pop_route: string,
    userIso: string,
    stdc: string,
    opname: string,
    country: string,
    port_from: string,
    port_to: string,
    baseData: string,
    callback: string,
}
